version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000"
      - "5001"
    env_file:
      - .env
    environment:
      - JWT_KEY
      - JWT_ISSUER
      - JWT_AUDIENCE
      - JWT_EXPIRY_IN_MINUTES
      - TELEGRAM_BOT_TOKEN
      - MARKDOWN_PROD_PATH
      - LOGGING__LOGLEVEL__DEFAULT
      - LOGGING__LOGLEVEL__MICROSOFT_ASPNETCORE
      - DEFAULT_CONNECTION
      - ALLOWEDHOSTS
      - ASPNETCORE_ENVIRONMENT=Production
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    depends_on:
      - db

  db:
    image: postgres:17
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-inapi_db}
    restart: on-failure

volumes:
  pgdata:
    external: true
