version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
      - "8081:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    env_file:
      - .env
    volumes:
      - data-protection-keys:/root/.aspnet/DataProtection-Keys
    restart: unless-stopped
volumes:
  data-protection-keys: