version: "3.8"

services:
  api:
    container_name: inapi-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:5000"   # HTTP
      - "8081:5001"   # HTTPS или второй сервисный порт
    env_file:
      - .env
    environment:
      - JWT_KEY
      - JWT_ISSUER
      - JWT_AUDIENCE
      - JWT_EXPIRY_IN_MINUTES
      - TELEGRAM_BOT_TOKEN
      - MARKDOWN_PROD_PATH
      - LOGGING__LOGLEVEL__DEFAULT
      - LOGGING__LOGLEVEL__MICROSOFT_ASPNETCORE
      - DEFAULT_CONNECTION
      - ALLOWEDHOSTS
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - data-protection-keys:/root/.aspnet/DataProtection-Keys
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  data-protection-keys:
