version: "3.8"

services:
  api:
    image: tor4narek/inapi:latest
    profiles: ["production"]
    ports:
      - "8080:5000"
      - "8081:5001"
    env_file:
      - .env
    environment:
      - JWT_KEY=${JWT_KEY}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - JWT_EXPIRY_IN_MINUTES=${JWT_EXPIRY_IN_MINUTES}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - MARKDOWN_PROD_PATH=${MARKDOWN_PROD_PATH}
      - LOGGING__LOGLEVEL__DEFAULT=${LOGGING__LOGLEVEL__DEFAULT}
      - LOGGING__LOGLEVEL__MICROSOFT_ASPNETCORE=${LOGGING__LOGLEVEL__MICROSOFT_ASPNETCORE}
      - DEFAULT_CONNECTION=${DEFAULT_CONNECTION}
      - ALLOWEDHOSTS=${ALLOWEDHOSTS}
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - data-protection-keys:/root/.aspnet/DataProtection-Keys
    restart: always

volumes:
  data-protection-keys:
